### ISSUE TITLE
Building Search Activity

### ISSUE THREAD

**Issue by RaynerKristanto** [vnguyen70/GTInteractive#2]
Implement BuildingSearchActivity.

Acceptance Criteria:
- Search field appears at top of screen.
- Clicking/tapping into search field reveals a drop-down-select of the user's recent searches (SuggestionProvider?). Clicking on a recent search populates the search field and executes that search query.
- Every time the user types a letter into the search field, execute a search with the current query and update the drop-down-select to show the new results. This should only happen when the user TYPES a letter, not when the user deletes a letter.
- When the user clicks on a building in the results list, the building details activity for that building is opened.

**Comment by vnguyen70** [comment]
Should the UI and functionality be separated into 2 tasks? IMO, I'd consider Search itself an epic. Inside the epic, there should be 1 task for UI and 1 task for search functionality. Inside that will be the acceptance criteria (i.e. Pressing search button sends query inside text field to database, retrieves data, etc.). Just food for thought. :)

**Comment by kaliqwang** [comment]
Actually - that's what I was going for here. This ticket is the UI ticket for creating the xml layout and linking the UI elements to various function calls. Another person will implement the actual functions themselves (Building Search Functions ticket).
