### ISSUE TITLE
Refactor XML

### ISSUE THREAD

**Issue by kaliqwang** [vnguyen70/GTInteractive#54]
## General:
- **STRICT: All id names, string names, and dimension names should be snake_case, not camelCase.
- **STRICT: all snake_case naming should be from least descriptive to most descriptive. Examples: activity_list_events, not activity_events_list. The reason is 1) consistency and 2) natural organization (e.g. all activity_list_x files will be naturally grouped together alphabetically).

### First Pass (clean up attributes):
- make sure every layout has correct tools:context attribute set
- remove all unnecessary attributes (only minimal attributes necessary); example: if an element only needs a TopToTop and LeftToLeft constraint in order to be properly positioned, remove the Right and Bottom constraints. Also, remove all "horizontal_bias" and "vertical_bias" constraints, if any.
- make attributes listed as consistent as possible from element to element; example: if you specify "android:textSize" in one TextView, specify it in all the others too
- **STRICT: ordering of attributes must always be consistent from element to element. Doesn't matter what the order is - as long as it is always the same. An example order would be: "layout_width" / "layout_height" first, then "layout_margin" if any, then "padding" if any, then all "android:" attributes related to text if any, then all other "android:" attributes if any, then all "app_layout_constraint" attributes.

### Second Pass (fix all id values):
- **STRICT: id for each element should have the following format: "type_description", where "type" is just a one-word identifier (e.g. "text" for TextView, "image" for ImageView, "edit" for EditText, etc. - doesn't matter what word you choose - just make consistent for entire app). For example, if a TextView is holding an event's name, then the id of that TextView should be "text_event_name". The ImageView holding the place image should be "image_place" or "image_place_image" works too.
- **STRICT: make sure that in Java code, the local reference to the view is *ALWAYS* the id of that view, except camelCase instead of snake_case. Example: TextView textEventName = findViewById(R.id.text_event_name). If there are name clashes, make the IDs more specific. The Java files you mainly need to check are the adapter and activity files.
- **STRICT: the only elements that should have an ID are those that are referenced in code. If there are any static TextViews, say a label that says "Place Name: ", it should not have an ID.

### Third Pass (refactor dimension and String values into dimens.xml and strings.xml):
- self explanatory - refactor all dimension values (e.g. "16dp") into dimens.xml. Easiest way to do this is to click on a dimension value (e.g. "16dp"), press ALT+ENTER, select "Extract dimension resource", and specify the resource name (use the aforementioned naming conventions - snake_case, and least descriptive to most descriptive). Then, you can just CTRL+F all the "16dp" values in the file and replace it with a reference to the new dimens resource. Similarly - refactor all String values into strings.xml. Note: don't use the same resource for different purposes, even if the values are the same. For example, if padding and margin are both "16dp", still create separate "list_item_padding" and "list_item_margin" resources, both with the same value of "16dp".

## res/values:
- dimens.xml - organize/group by related; one line of space between each group; naming consistency
- strings.xml - organize/group by related; one line of space between each group; naming consistency

## Acceptance Criteria:
- consistency and thoroughness

**Comment by Jonathan-Hernandez14** [comment]
xmls up to the activity_map_activuty.ml have been refactored. found a bug trying to click on events
